node {


        stage('Build') {

                sh 'echo hi'

        }
        stage('Test') {

                sh 'echo testing'

            post {
                always {
                    sh 'echo results'
                }
            }
        }
        stage('Deliver') {

                sh 'echo test branch'

        }
    
}
