node {


        stage('Build') {

                sh 'echo hi'
                sh 'ls'

        }
        try{
        stage('Test') {

                sh 'echo testing'
        }
        }
        catch(e){
                echo "error"
        }
        finally{
                echo currentBuild.result
                if (currentBuild.result=="SUCCESS") {
                        echo "successful pipeline"
                }
        
        }
        stage('Deliver') {

                sh 'echo test branch'

        }
    
}
