node {


        stage('Build') {

                sh 'echo hi'

        }
        try{
        stage('Test') {

                sh 'echo testing'
        }
        }
        catch(e){
                echo "error"
        }
        finally{
                if (currentBuild.result == 'SUCCESS') {
                        echo "success"
                }
        
        }
        stage('Deliver') {

                sh 'echo test branch'

        }
    
}
